name: "Publish releases to FlakeHub"
on:
  push:
    tags:
      - "[a-zA-Z0-9]+-v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/github-script@v6
        id: split
        env:
          INPUT_TAG: "${{ inputs.tag }}"
        with:
          script: |
            "use strict";
            const extractTagFromRef = (ref) => {
                if (ref.startsWith("refs/tags/")) {
                    const parts = ref.split("/");
                    if (parts.length != 3) {
                        console.log(`Tried to extract a tag from '${ref}' but it didn't split by '/' into three parts.`);
                        return undefined;
                    }
                    return parts[2];
                }
                else {
                    console.log(`Tried to extract a tag from '${ref}' but it didn't start with 'refs/tags/'`);
                    return undefined;
                }
            };
            const extractVersionDirectory = (tag, ref) => {
                const selected_tag = input_tag || extractTagFromRef(ref);
                if (!selected_tag) {
                    console.log(`No valid tag identified from the ref ('${ref}') or inputs ('${input_tag}').`);
                    return undefined;
                }
                const parts = selected_tag.split('-');
                if (parts.length != 2) {
                    console.log(`The tag '${selected_tag}' didn't split by '-' into two parts, where the first part should be the directory and the second should be the version.`);
                    return undefined;
                }
                return {
                    directory: parts[0],
                    version: parts[1],
                };
            };
            const input_tag = "go-v0.1.0";
            const ref = "refs/tags/go-v0.1.1695299916";
            console.log(extractVersionDirectory(input_tag, ref));
          

      # - uses: "actions/checkout@v3"
      #   with:
      #     ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      # - uses: "DeterminateSystems/nix-installer-action@main"
      # - run: "echo publishing ${} at version ${} as GetPsyched/${}-env"
      # - uses: "DeterminateSystems/flakehub-push@main"
      #   with:
      #     directory: "cpp"
      #     name: "GetPsyched/cpp-env"
      #     tag: "${{ steps.split.outputs._1 }}"
      #     visibility: "public"
