name: "Publish releases to FlakeHub"
on:
  push:
    tags:
      - "[a-zA-Z0-9]+-v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/github-script@v6
        id: split
        env:
          INPUT_TAG: "${{ inputs.tag }}"
        with:
          script: |
            console.log(`${ process.env['INPUT_TAG'] || "undefined" }`)
            console.log(`${ github.context?.ref_name || "undefined" }`)



#            "${{ inputs.tag }}"
#          ${{ github.ref_name }}
      # - uses: "actions/checkout@v3"
      #   with:
      #     ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      # - uses: "DeterminateSystems/nix-installer-action@main"
      # - run: "echo publishing ${} at version ${} as GetPsyched/${}-env"
      # - uses: "DeterminateSystems/flakehub-push@main"
      #   with:
      #     directory: "cpp"
      #     name: "GetPsyched/cpp-env"
      #     tag: "${{ steps.split.outputs._1 }}"
      #     visibility: "public"
